pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=master
      # this serves as ALL check has to pass as we have actually around 10 tests in total
      - "#status-success>=18"
      # no conflict with master branch
      - -conflict
      # was not closed yet
      - -closed
      # filter-out GH draft PRs
      - -draft
    actions:
      delete_head_branch: {}
      merge:
        # https://doc.mergify.io/merge-action.html#strict-merge
        # (on head branch) $ git merge --no-ff base
        # (on head branch) # Wait for CI to go green
        # (on head branch) # Squash all commits
        # (on base branch) $ git merge --ff head
        strict: true
        method: squash
      comment:
        message: Great job! =)

  - name: warn on conflicts
    conditions:
      - conflict
      # filter-out GH draft PRs
      - -draft
    actions:
      comment:
        message: This pull request is now in conflict... :(
